#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-phonebook-mysql-update
#
my $event = "nethserver-phonebook-mysql-update";

event_actions ($event , qw(
    initialize-default-databases 00
    nethserver-unixODBC-conf 40
    nethserver-phonebook-mysql-conf 60
));

templates2events ('/etc/odbc.ini',$event);
templates2events ('/usr/share/phonebookjs/config.json',$event);
templates2events ('/etc/phonebook/destination-import.json',$event);
event_services($event, qw(
    phonebookjs restart
));


#
# nethserver-phonebook-mysql-save
#
$event = "nethserver-phonebook-mysql-save";

event_actions ($event , qw(
    firewall-adjust 70
));

templates2events ('/usr/share/phonebookjs/config.json',$event);
event_services($event, qw(
    phonebookjs restart
));


#
# restore-config event
#
event_actions('post-restore-config', qw(
    nethserver-phonebook-mysql-fixldap 19
));
