#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-phonebook-mysql-update
#
my $event = "nethserver-phonebook-mysql-update";

event_actions ($event , qw(
    initialize-default-databases 00
    nethserver-unixODBC-conf 40
    nethserver-phonebook-mysql-conf 60
));

templates2events ('/etc/odbc.ini',$event);
templates2events ('/usr/share/phonebookjs/config.json',$event);
templates2events ('/usr/share/phonebookjs/config_ldaps.json',$event);
templates2events ('/etc/phonebook/destination-import.json',$event);
templates2events ('/usr/share/phonebookjs/fullchain.pem',$event);
event_services($event, qw(
    phonebookjs restart
    phonebookjss restart
));


#
# nethserver-phonebook-mysql-save
#
$event = "nethserver-phonebook-mysql-save";

event_actions ($event , qw(
    nethserver-phonebook-mysql-clear 60
    nethserver-phonebook-mysql-sync 70
));

event_services($event, qw(
    phonebookjs try-restart
    phonebookjss try-restart
));

#
# nethserver-phonebook-mysql-fwsave
#
$event = "nethserver-phonebook-mysql-fwsave";

event_actions ($event , qw(
    firewall-adjust 70
));

templates2events ('/usr/share/phonebookjs/config.json',$event);
templates2events ('/usr/share/phonebookjs/config_ldaps.json',$event);
event_services($event, qw(
    phonebookjs restart
    phonebookjss restart
));

#
# restore-config event
#
event_actions('post-restore-config', qw(
    nethserver-phonebook-mysql-fixldap 19
    nethserver-phonebook-mysql-conf 60
));

#
# Certificate-update event
#
$event = "certificate-update";

templates2events ('/usr/share/phonebookjs/fullchain.pem',$event);

event_services($event, qw(
    phonebookjss restart
));

