#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = nethserver-phonebook-mysql-update

event_actions ($event , 'initialize-default-databases 00');

templates2events ('/usr/share/phonebooks/phonebook.sql',$event);

event_link ("nethserver-phonebook-mysql-install", $event, "98");

