#!/bin/bash

# Publish all configured phonebook into one phonebook

# empty phonebook table
mysql phonebook -e "truncate phonebook"


# Export sogo phonebook if requested
sogo_status=`/sbin/e-smith/config getprop phonebook sogo`
if [ "X$sogo_status" != "Xdisabled" ]; then
        /usr/share/phonebooks/sogo_export.php $sogo_status
fi

# Execute all custom scripts
for i in `find /usr/share/phonebooks/scripts/`; do
        if [ -f $i ] && [ -x $i ]; then
                $i
        fi
done

# Export data in ldap if requested
ldap_status=`/sbin/e-smith/config getprop phonebook ldap`
if [ "X$ldap_status" == "Xenabled" ]; then
	/usr/share/phonebooks/phonebook2ldap
fi

