#!/bin/bash

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

mysql -f << END

use phonebook;

drop table if exists ldap_oc_mappings;
create table ldap_oc_mappings
 (
        id integer unsigned not null primary key auto_increment,
        name varchar(64) not null,
        keytbl varchar(64) not null,
        keycol varchar(64) not null,
        create_proc varchar(255),
        delete_proc varchar(255),
        expect_return tinyint not null
);

drop table if exists ldap_attr_mappings;
create table ldap_attr_mappings
 (
        id integer unsigned not null primary key auto_increment,
        oc_map_id integer unsigned not null references ldap_oc_mappings(id),
        name varchar(255) not null,
        sel_expr varchar(255) not null,
        sel_expr_u varchar(255),
        from_tbls varchar(255) not null,
        join_where varchar(255),
        add_proc varchar(255),
        delete_proc varchar(255),
        param_order tinyint not null,
        expect_return tinyint not null
);

drop table if exists ldap_entries;
create table ldap_entries
 (
        id integer unsigned not null primary key auto_increment,
        dn varchar(255) not null,
        oc_map_id integer unsigned not null references ldap_oc_mappings(id),
        parent int NOT NULL ,
        keyval int NOT NULL 
);

alter table ldap_entries add 
        constraint unq1_ldap_entries unique
        (
                oc_map_id,
                keyval
        );  

alter table ldap_entries add
        constraint unq2_ldap_entries unique
        (
                dn
        );  

drop table if exists ldap_entry_objclasses;
create table ldap_entry_objclasses
 (
        entry_id integer not null references ldap_entries(id),
        oc_name varchar(64)
 );


INSERT INTO ldap_attr_mappings VALUES (1,1,'cn','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (2,1,'sn','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (3,1,'givenName','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (4,1,'telephoneNumber','workphone','workphone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (5,1,'facsimiletelephonenumber','fax','fax','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (6,1,'mail','workemail','workemail','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (7,1,'o','company','company','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (8,1,'mobile','cellphone','cellphone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (9,1,'streetaddress','workstreet','workstreet','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (10,1,'homePhone','homephone','homephone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (11,1,'l','workcity','workcity','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (12,1,'countryName','workcountry','workcountry','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (13,1,'stateOrProvinceName','workprovince','workprovince','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (14,1,'personalTitle','title','title','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (15,1,'postalCode','workpostalcode','workpostalcode','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (16,1,'displayName','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (17,1,'ou','company','company','phonebook',NULL,NULL,NULL,3,0);

INSERT INTO ldap_entries VALUES (1,'dc=phonebook,dc=nh',3,0,1);
INSERT INTO ldap_entries VALUES (2,'ou=Referral,dc=phonebook,dc=nh',4,0,1);

INSERT INTO ldap_entry_objclasses VALUES (1,'dcObject');
INSERT INTO ldap_entry_objclasses VALUES (7,'extensibleObject');

INSERT INTO ldap_oc_mappings VALUES (1,'inetOrgPerson','phonebook','id',NULL,NULL,0);
INSERT INTO ldap_oc_mappings VALUES (2,'document','phonebook','id',NULL,NULL,0);
INSERT INTO ldap_oc_mappings VALUES (3,'organization','phonebook','id',NULL,NULL,0);
INSERT INTO ldap_oc_mappings (id,name,keytbl,keycol,create_proc,delete_proc,expect_return) VALUES (4,'referral','referrals','id',NULL,NULL,0);


REPLACE INTO ldap_entries (dn,oc_map_id,parent,keyval) 
  SELECT CONCAT('cn=',if(name IS NOT NULL AND name != '' AND name != ' ',name,company),',','dc=phonebook,dc=nh'),1,1,id 
    FROM phonebook;
END
