#!/bin/bash
mysql -f << END

use phonebook;

DROP TABLE IF EXISTS ldap_attr_mappings;
CREATE TABLE ldap_attr_mappings (
  id int(10) unsigned NOT NULL auto_increment,
  oc_map_id int(10) unsigned NOT NULL default '0',
  name varchar(255) NOT NULL default '',
  sel_expr varchar(255) NOT NULL default '',
  sel_expr_u varchar(255) default NULL,
  from_tbls varchar(255) NOT NULL default '',
  join_where varchar(255) default NULL,
  add_proc varchar(255) default NULL,
  delete_proc varchar(255) default NULL,
  param_order tinyint(4) NOT NULL default '0',
  expect_return tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (id)
) TYPE=MyISAM;


INSERT INTO ldap_attr_mappings VALUES (1,1,'cn','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (2,1,'sn','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (3,1,'givenName','name','name','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (4,1,'telephoneNumber','workphone','workphone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (5,1,'facsimiletelephonenumber','fax','fax','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (6,1,'mail','workemail','workemail','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (7,1,'o','company','company','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (8,1,'mobile','cellphone','cellphone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (9,1,'streetaddress','workstreet','workstreet','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (10,1,'homePhone','homephone','homephone','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (11,1,'l','workcity','workcity','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (12,1,'countryName','workcountry','workcountry','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (13,1,'stateOrProvinceName','workprovince','workprovince','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (14,1,'personalTitle','title','title','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (15,1,'postalCode','workpostalcode','workpostalcode','phonebook',NULL,NULL,NULL,3,0);
INSERT INTO ldap_attr_mappings VALUES (16,1,'displayName','name','name','phonebook',NULL,NULL,NULL,3,0);


DROP TABLE IF EXISTS ldap_entries;
CREATE TABLE ldap_entries (
  id int(10) unsigned NOT NULL auto_increment,
  dn varchar(255) NOT NULL default '',
  oc_map_id int(10) unsigned NOT NULL default '0',
  parent int(11) NOT NULL default '0',
  keyval int(11) NOT NULL default '0',
  PRIMARY KEY  (id),
  UNIQUE KEY dn (dn),
  UNIQUE KEY oc_map_id (oc_map_id,keyval)
) TYPE=MyISAM;

INSERT INTO ldap_entries VALUES (1,'dc=rubrica',2,0,1);
INSERT INTO ldap_entries VALUES (2,'ou=Referral,dc=rubrica',3,0,1);

REPLACE INTO ldap_entries (dn,oc_map_id,parent,keyval) 
  SELECT CONCAT('cn=',if(name IS NOT NULL AND name != '' AND name != ' ',name,company),',','dc=rubrica'),1,1,id 
    FROM phonebook;


DROP TABLE IF EXISTS ldap_entry_objclasses;
CREATE TABLE ldap_entry_objclasses (
  entry_id int(11) NOT NULL default '0',
  oc_name varchar(64) default NULL
) TYPE=MyISAM;


INSERT INTO ldap_entry_objclasses VALUES (1,'dcObject');
INSERT INTO ldap_entry_objclasses VALUES (7,'extensibleObject');


DROP TABLE IF EXISTS ldap_oc_mappings;
CREATE TABLE ldap_oc_mappings (
  id int(10) unsigned NOT NULL auto_increment,
  name varchar(64) NOT NULL default '',
  keytbl varchar(64) NOT NULL default '',
  keycol varchar(64) NOT NULL default '',
  create_proc varchar(255) default NULL,
  delete_proc varchar(255) default NULL,
  expect_return tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (id)
) TYPE=MyISAM;


INSERT INTO ldap_oc_mappings VALUES (1,'inetOrgPerson','phonebook','id',NULL,NULL,0);
INSERT INTO ldap_oc_mappings VALUES (2,'document','phonebook','id',NULL,NULL,0);

DROP TABLE IF EXISTS ldap_referrals;
CREATE TABLE ldap_referrals (
  entry_id int(11) NOT NULL default '0',
  url text NOT NULL
) TYPE=MyISAM;

END
