#!/bin/sh

# Publish all configured phonebook into one phonebook

# empty phonebook table
/usr/bin/mysql -h ${PHONEBOOK_DB_HOST} ${PHONEBOOK_DB_NAME} -u${PHONEBOOK_DB_USER} -p${PHONEBOOK_DB_PASS} -e "DELETE FROM phonebook WHERE sid_imported IS NULL"

# Export nethcti phonebook if requested
/usr/share/phonebooks/nethcti_export.php

# Export nethvoice speeddial if requested
/usr/share/phonebooks/speeddial_and_rapidcode_export.php

# Export nethvoice extensions
/usr/share/phonebooks/nethvoice_extensions_export.php

# Execute all custom scripts
for i in $(find /usr/share/phonebooks/scripts/); do
        if [ -f $i ] && [ -x $i ]; then
                $i
        fi
done

# Execute all custom post scripts
for i in $(find /usr/share/phonebooks/post_scripts/); do
        if [ -f $i ] && [ -x $i ]; then
                $i
        fi
done

