#!/bin/bash

#
# Create phonebook database on new installations.
# Add missing fields on existing installations.
#

db_pwd=$(perl -e "use NethServer::Password; print NethServer::Password::store('PhonebookDBPasswd')")

db_exists=$(/usr/bin/mysql --defaults-file=/root/.my.cnf -e "select count(*) from information_schema.tables where table_type = 'BASE TABLE' and table_schema = 'phonebook'" | tail -n1)

if [[ $db_exists == '0' ]]; then
    # create phonebook database
    mysql --defaults-file=/root/.my.cnf <<EOF
CREATE DATABASE IF NOT EXISTS phonebook;

USE phonebook;

CREATE TABLE IF NOT EXISTS phonebook (
  id int(11) NOT NULL auto_increment,
  owner_id varchar(255) NOT NULL default '',
  type varchar(255) NOT NULL default '',
  homeemail varchar(255) default NULL,
  workemail varchar(255) default NULL,
  homephone varchar(25) default NULL,
  workphone varchar(25) default NULL,
  cellphone varchar(25) default NULL,
  fax varchar(25) default NULL,
  title varchar(255) default NULL,
  company varchar(255) default NULL,
  notes text,
  name varchar(255) default NULL,
  homestreet varchar(255) default NULL,
  homepob varchar(10) default NULL,
  homecity varchar(255) default NULL,
  homeprovince varchar(255) default NULL,
  homepostalcode varchar(255) default NULL,
  homecountry varchar(255) default NULL,
  workstreet varchar(255) default NULL,
  workpob varchar(10) default NULL,
  workcity varchar(255) default NULL,
  workprovince varchar(255) default NULL,
  workpostalcode varchar(255) default NULL,
  workcountry varchar(255) default NULL,
  url varchar(255) default NULL,
  sid_imported varchar(255) default NULL,
  PRIMARY KEY  (id),
  KEY owner_idx (owner_id),
  KEY wemail_idx (workemail),
  KEY hemail_idx (homeemail),
  KEY name_idx (name),
  KEY hphone_idx (homephone),
  KEY wphone_idx (workphone),
  KEY cphone_idx (cellphone),
  KEY fax_idx (fax),
  KEY company_idx (company)
) ENGINE=MyISAM CHARSET=UTF8;

EXISTS=$(/usr/bin/mysql --defaults-file=/root/.my.cnf -e "SHOW KEYS FROM phonebook.phonebook WHERE Key_name='company_idx'");
if [[ $EXISTS == "" ]]; then
  /usr/bin/mysql --defaults-file=/root/.my.cnf -e "ALTER TABLE phonebook.phonebook ADD INDEX company_idx(company)"
fi

USE mysql;

GRANT ALL on phonebook.* TO pbookuser identified by '$db_pwd';

FLUSH privileges;
EOF

else
    # update existing table, if needed
    mysql --defaults-file=/root/.my.cnf -BN mysql -e "SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='phonebook' AND COLUMN_NAME='sid_imported' AND TABLE_NAME='phonebook'" | grep -q sid_imported

    if [[ $? -gt 0 ]]; then
        # add missing fields
        echo "[NOTICE] Adding sid_imported field"
        mysql --defaults-file=/root/.my.cnf phonebook -e "ALTER TABLE phonebook ADD sid_imported varchar(255) default NULL"
    fi
fi
